CREATE TABLE `ESTADO_CLIENTE`
(
    `ID`   int         NOT NULL AUTO_INCREMENT,
    `TIPO` varchar(20) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `CLIENTE`
(
    `ID`                int      NOT NULL AUTO_INCREMENT,
    `FECHA_INICIO`      datetime NOT NULL,
    `ESTADO_CLIENTE_ID` int      NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `ESTADO_CLIENTE_ID` (`ESTADO_CLIENTE_ID`),
    CONSTRAINT `CLIENTE_ibfk_1` FOREIGN KEY (`ESTADO_CLIENTE_ID`) REFERENCES `ESTADO_CLIENTE` (`ID`)
);

CREATE TABLE `TIPO_USUARIO`
(
    `ID`   int NOT NULL AUTO_INCREMENT,
    `TIPO` varchar(20) DEFAULT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `USUARIO`
(
    `ID`           int         NOT NULL,
    `NIF`          varchar(9)  NOT NULL,
    `CONTRASENA`   varchar(45) NOT NULL,
    `TIPO_USUARIO` int         NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `TIPO_USUARIO` (`TIPO_USUARIO`),
    CONSTRAINT `USUARIO_ibfk_1` FOREIGN KEY (`ID`) REFERENCES `CLIENTE` (`ID`),
    CONSTRAINT `USUARIO_ibfk_2` FOREIGN KEY (`TIPO_USUARIO`) REFERENCES `TIPO_USUARIO` (`ID`)
);

CREATE TABLE `CONVERSACION`
(
    `ID`             int      NOT NULL AUTO_INCREMENT,
    `EMISOR`         int      NOT NULL,
    `RECEPTOR`       int      NOT NULL DEFAULT '27',
    `TERMINADA`      tinyint  NOT NULL DEFAULT '0',
    `FECHA_CREACION` datetime NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `EMISOR` (`EMISOR`),
    KEY `RECEPTOR` (`RECEPTOR`),
    CONSTRAINT `EMISOR` FOREIGN KEY (`EMISOR`) REFERENCES `USUARIO` (`ID`),
    CONSTRAINT `RECEPTOR` FOREIGN KEY (`RECEPTOR`) REFERENCES `USUARIO` (`ID`)
);

CREATE TABLE `DIVISA`
(
    `ID`           int         NOT NULL AUTO_INCREMENT,
    `NOMBRE`       varchar(40) NOT NULL,
    `EQUIVALENCIA` double      NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `ENTIDAD_BANCARIA`
(
    `ID`     int         NOT NULL AUTO_INCREMENT,
    `NOMBRE` varchar(45) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `ESTADO_CUENTA`
(
    `ID`   int         NOT NULL AUTO_INCREMENT,
    `TIPO` varchar(30) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `CUENTA_BANCO`
(
    `ID`                     int         NOT NULL AUTO_INCREMENT,
    `DIVISA_ID`              int         NOT NULL,
    `IBAN_CUENTA`            varchar(24) NOT NULL,
    `SALDO`                  double      NOT NULL,
    `SWIFT`                  varchar(11) NOT NULL,
    `PAIS`                   varchar(45) NOT NULL,
    `FECHA_APERTURA`         datetime    NOT NULL,
    `FECHA_CIERRE`           datetime             DEFAULT NULL,
    `TITULAR_ID`             int         NOT NULL,
    `ENTIDAD_BANCARIA_ID`    int         NOT NULL,
    `ESTADO_CUENTA_ID`       int         NOT NULL,
    `TIPO_CUENTA_SOSPECHOSO` int         NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `IBAN_CUENTA` (`IBAN_CUENTA`),
    KEY `TITULAR_ID` (`TITULAR_ID`),
    KEY `ENTIDAD_BANCARIA_ID` (`ENTIDAD_BANCARIA_ID`),
    KEY `ESTADO_CUENTA_ID` (`ESTADO_CUENTA_ID`),
    KEY `CUENTA_BANCO_DIVISA_ID_fk` (`DIVISA_ID`),
    CONSTRAINT `CUENTA_BANCO_DIVISA_ID_fk` FOREIGN KEY (`DIVISA_ID`) REFERENCES `DIVISA` (`ID`),
    CONSTRAINT `CUENTA_BANCO_ibfk_1` FOREIGN KEY (`TITULAR_ID`) REFERENCES `CLIENTE` (`ID`),
    CONSTRAINT `CUENTA_BANCO_ibfk_2` FOREIGN KEY (`ENTIDAD_BANCARIA_ID`) REFERENCES `ENTIDAD_BANCARIA` (`ID`),
    CONSTRAINT `CUENTA_BANCO_ibfk_3` FOREIGN KEY (`ESTADO_CUENTA_ID`) REFERENCES `ESTADO_CUENTA` (`ID`)
);

CREATE TABLE `CUENTA_SOSPECHOSA`
(
    `ID` int NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `CUENTA_SOSPECHOSA_CUENTA_BANCO_ID_fk` FOREIGN KEY (`ID`) REFERENCES `CUENTA_BANCO` (`ID`)
);

CREATE TABLE `DIRECCION`
(
    `ID`                    int         NOT NULL AUTO_INCREMENT,
    `CALLE`                 varchar(45) NOT NULL,
    `NUMERO`                int         NOT NULL,
    `PLANTA_PUERTA_OFICINA` varchar(45) DEFAULT NULL,
    `CIUDAD`                varchar(45) NOT NULL,
    `REGION`                varchar(45) NOT NULL,
    `CODIGO_POSTAL`         int         NOT NULL,
    `PAIS`                  varchar(45) NOT NULL,
    `VALIDA`                tinyint     DEFAULT NULL,
    `CLIENTE_ID`            int         NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `CLIENTE_ID` (`CLIENTE_ID`),
    CONSTRAINT `DIRECCION_ibfk_1` FOREIGN KEY (`CLIENTE_ID`) REFERENCES `CLIENTE` (`ID`)
);

CREATE TABLE `EMPRESA`
(
    `ID`     int         NOT NULL,
    `NOMBRE` varchar(45) NOT NULL,
    `CIF`    varchar(9)  NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `CIF` (`CIF`),
    CONSTRAINT `EMPRESA_ibfk_1` FOREIGN KEY (`ID`) REFERENCES `CLIENTE` (`ID`)
);

CREATE TABLE `TIPO_CLIENTE_RELACIONADO`
(
    `ID`   int NOT NULL AUTO_INCREMENT,
    `TIPO` varchar(20) DEFAULT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `PERSONA`
(
    `ID`               int         NOT NULL,
    `NOMBRE`           varchar(45) NOT NULL,
    `APELLIDO1`        varchar(45) NOT NULL,
    `APELLIDO2`        varchar(45) DEFAULT NULL,
    `FECHA_NACIMIENTO` date        NOT NULL,
    `DNI`              varchar(9)  NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `DNI` (`DNI`),
    CONSTRAINT `PERSONA_ibfk_1` FOREIGN KEY (`ID`) REFERENCES `CLIENTE` (`ID`)
);

CREATE TABLE `EMPRESA_CLIENTE`
(
    `ID`         int NOT NULL AUTO_INCREMENT,
    `ID_TIPO`    int NOT NULL,
    `ID_EMPRESA` int NOT NULL,
    `ID_PERSONA` int NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `ID_TIPO` (`ID_TIPO`),
    KEY `ID_EMPRESA` (`ID_EMPRESA`),
    KEY `ID_PERSONA` (`ID_PERSONA`),
    CONSTRAINT `EMPRESA_CLIENTE_ibfk_1` FOREIGN KEY (`ID_TIPO`) REFERENCES `TIPO_CLIENTE_RELACIONADO` (`ID`),
    CONSTRAINT `EMPRESA_CLIENTE_ibfk_2` FOREIGN KEY (`ID_EMPRESA`) REFERENCES `EMPRESA` (`ID`),
    CONSTRAINT `EMPRESA_CLIENTE_ibfk_3` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`)
);

CREATE TABLE `TIPO_PERSONA_RELACIONADA`
(
    `ID`   int         NOT NULL AUTO_INCREMENT,
    `TIPO` varchar(20) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `EMPRESA_PERSONA`
(
    `ID`         int NOT NULL AUTO_INCREMENT,
    `ID_TIPO`    int NOT NULL,
    `ID_EMPRESA` int NOT NULL,
    `ID_PERSONA` int NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `ID_TIPO` (`ID_TIPO`),
    KEY `ID_EMPRESA` (`ID_EMPRESA`),
    KEY `ID_PERSONA` (`ID_PERSONA`),
    CONSTRAINT `EMPRESA_PERSONA_ibfk_1` FOREIGN KEY (`ID_TIPO`) REFERENCES `TIPO_PERSONA_RELACIONADA` (`ID`),
    CONSTRAINT `EMPRESA_PERSONA_ibfk_2` FOREIGN KEY (`ID_EMPRESA`) REFERENCES `EMPRESA` (`ID`),
    CONSTRAINT `EMPRESA_PERSONA_ibfk_3` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`)
);

CREATE TABLE `MENSAJE`
(
    `ID`           int          NOT NULL AUTO_INCREMENT,
    `CONVERSACION` int          NOT NULL,
    `CONTENIDO`    varchar(500) NOT NULL,
    `FECHA`        datetime     NOT NULL,
    `EMISOR`       int          NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `EMISOR` (`EMISOR`),
    KEY `MENSAJE_ibfk_1` (`CONVERSACION`),
    CONSTRAINT `MENSAJE_ibfk_1` FOREIGN KEY (`CONVERSACION`) REFERENCES `CONVERSACION` (`ID`),
    CONSTRAINT `MENSAJE_ibfk_2` FOREIGN KEY (`EMISOR`) REFERENCES `USUARIO` (`ID`)
);

CREATE TABLE `TRANSACCION`
(
    `ID`                int      NOT NULL AUTO_INCREMENT,
    `FECHA_INSTRUCCION` datetime NOT NULL,
    `FECHA_EJECUCION`   datetime NOT NULL,
    `CANTIDAD`          double   NOT NULL,
    `CUENTA_ORIGEN`     int      NOT NULL,
    `CUENTA_DESTINO`    int      NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `CUENTA_ORIGEN` (`CUENTA_ORIGEN`),
    KEY `CUENTA_DESTINO` (`CUENTA_DESTINO`),
    CONSTRAINT `TRANSACCION_ibfk_1` FOREIGN KEY (`CUENTA_ORIGEN`) REFERENCES `CUENTA_BANCO` (`ID`),
    CONSTRAINT `TRANSACCION_ibfk_2` FOREIGN KEY (`CUENTA_DESTINO`) REFERENCES `CUENTA_BANCO` (`ID`)
);

CREATE TABLE `OPERACION`
(
    `ID`             int NOT NULL AUTO_INCREMENT,
    `PERSONA_ID`     int NOT NULL,
    `TRANSACCION_ID` int NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `PERSONA_ID` (`PERSONA_ID`),
    KEY `TRANSACCION_ID` (`TRANSACCION_ID`),
    CONSTRAINT `OPERACION_ibfk_1` FOREIGN KEY (`PERSONA_ID`) REFERENCES `PERSONA` (`ID`),
    CONSTRAINT `OPERACION_ibfk_2` FOREIGN KEY (`TRANSACCION_ID`) REFERENCES `TRANSACCION` (`ID`)
);
