INSERT INTO DIVISA (NOMBRE, EQUIVALENCIA) VALUES ('EUR', 1.11);
INSERT INTO DIVISA (NOMBRE, EQUIVALENCIA) VALUES ('USD', 1);
INSERT INTO DIVISA (NOMBRE, EQUIVALENCIA) VALUES ('GBP', 1.24);

INSERT INTO ENTIDAD_BANCARIA (NOMBRE) VALUE ('BanK');

INSERT INTO ESTADO_CLIENTE (TIPO) VALUE ('Activo');
INSERT INTO ESTADO_CLIENTE (TIPO) VALUE ('Inactivo');
INSERT INTO ESTADO_CLIENTE (TIPO) VALUE ('Bloqueado');
INSERT INTO ESTADO_CLIENTE (TIPO) VALUE ('Cerrado');
INSERT INTO ESTADO_CLIENTE (TIPO) VALUE ('Pendiente');

INSERT INTO ESTADO_CUENTA (TIPO) VALUE ('Activa');
INSERT INTO ESTADO_CUENTA (TIPO) VALUE ('Bloqueada');
INSERT INTO ESTADO_CUENTA (TIPO) VALUE ('Cerrada');
INSERT INTO ESTADO_CUENTA (TIPO) VALUE ('Pendiente de activación');
INSERT INTO ESTADO_CUENTA (TIPO) VALUE ('Pendiente de desbloqueo');

INSERT INTO TIPO_CLIENTE_RELACIONADO (TIPO) VALUE ('Autorizado');
INSERT INTO TIPO_CLIENTE_RELACIONADO (TIPO) VALUE ('No autorizado');

INSERT INTO TIPO_PERSONA_RELACIONADA (TIPO) VALUE ('Socio');
INSERT INTO TIPO_PERSONA_RELACIONADA (TIPO) VALUE ('Representante');

INSERT INTO TIPO_USUARIO (TIPO) VALUE ('Cliente');
INSERT INTO TIPO_USUARIO (TIPO) VALUE ('Negocio');
INSERT INTO TIPO_USUARIO (TIPO) VALUE ('Asistente');